version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: rahman
      DB_NAME: todolist
      DB_USER: postgres
      DB_HOST: db
      DB_PASSWORD: root
      DB_PORT: "5432"
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
